### PR TITLE
implement and test string.split

### PR DESCRIPTION
**Pull request by xpe**
See issue #95

### CODE REVIEW

**Comment by connorskees** [comment]
thank you for this! i will push a new version to crates.io sometime this week

**Comment by Jieiku** [comment]
Thanks, this will be a useful feature to have! Will there be a new version number?

I see it is currently 0.13.2, I just want to know what to check to know when this feature is in :)

**Comment by connorskees** [comment]
Yep, this will go in a new bugfix version, so `0.13.3`. I will update this issue once it is published.

**Comment by connorskees** [comment]
This has been [published to crates.io](https://crates.io/crates/grass/0.13.3) as part of version 0.13.3.

**Pull request merged**
