### PR TITLE
Colors

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by pickfire** [comment]
Is there any reason why we need intermediate value and higher intermediate value? Why not just do parsing directly?

**Comment by connorskees** [comment]
That is largely a result of many refactors. Sass is very ambiguous. The higher intermediate value is used for evaluation and includes things like function calls and binary operations. The intermediate value is used for parsing and includes things like `Comma` and parentheses. 

Recent refactors should allow us to simplify the intermediate value, removing commas, parens, and bracketed lists. I think it will still be necessary to have 2 IRs, however.

**Comment by pickfire** [comment]
@connorskees What will happen if we only have one IR? Does dart-sass and libsass have 2 IR too?

**Comment by connorskees** [comment]
Certainly it would be possible to have no intermediate representation whatsoever, but that serves only to complicate places that deal with `Value`. Earlier versions of `Value` did have `BinaryOp`, `UnaryOp`, and `Paren` variants, but this meant that before ever using a `Value`, you were forced to evaluate it, and there was no way to use the compiler to amortize this evaluation or ensure that it was done.

Removing the IR used for parsing is a bit different. Until recently it *was* required in order to parse values. About 2 days ago I landed a change that *would* make it possible to entirely remove the IR used for parsing. This would, however, be a significant change and I would like to first clean up the parsing code to make this change easier to implement before going all the way in.

**Pull request merged**
