### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by striezel**
This pull request fixes some typos, no functional changes intended.

### CODE REVIEW

**Comment by connorskees** [comment]
Thanks!

**Comment by striezel** [comment]
@connorskees:
Somebody force-pushed commits to the master branch, and as a result this fix as well as the changes from #79 got removed from master. Was that intended?

**Comment by connorskees** [comment]
Thank you for mentioning this error. This was not intentional and I will fix this issue shortly.

**Comment by connorskees** [comment]
I've cherry-picked the lost commits and re-applied them onto master. Thank you again for these PRs, and for mentioning that the commits got lost during a force push. This is a bad habit I have for some of my personal projects, and is a bit embarrassing.

**Comment by striezel** [comment]
Thanks for re-applying them. :+1:

If you want to avoid losing commits by accident due to force push, then you can also enable branch protection for your projects: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches Among other things, branch protection disallows force pushes by default.

**Pull request merged**
